project_id = "rwdgnapajxcxktmewlxb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.bridge-pair]
    verify_jwt = false
  [functions.now-playing-ingest]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
