// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_events_default = defineTool({
  name: "list_my_events",
  title: "List my events",
  description: "List Decks events owned by the signed-in DJ (most recent first).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db(ctx).from("events").select("id, name, room_code, is_active, created_at").eq("dj_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-event-requests.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_event_requests_default = defineTool2({
  name: "list_event_requests",
  title: "List song requests for an event",
  description: "List song requests for a Decks event you can access, ordered by score then newest.",
  inputSchema: {
    event_id: z2.string().uuid().describe("Event UUID (from list_my_events)."),
    status: z2.enum(["pending", "approved", "played", "skipped", "removed"]).optional(),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db2(ctx).from("song_requests").select("id, title, artist, status, upvotes, downvotes, requester_name, created_at").eq("event_id", event_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q.order("upvotes", { ascending: false }).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-now-playing.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_now_playing_default = defineTool3({
  name: "get_now_playing",
  title: "Get now playing",
  description: "Return the current Now Playing track for a Decks event.",
  inputSchema: {
    event_id: z3.string().uuid().describe("Event UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db3(ctx).from("now_playing").select("title, artist, album_art, status, started_at, updated_at").eq("event_id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: data ? JSON.stringify(data) : "No track playing." }],
      structuredContent: { now_playing: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-recent-tips.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_tips_default = defineTool4({
  name: "list_recent_tips",
  title: "List recent tips",
  description: "List recent tips received by the signed-in DJ (most recent first).",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db4(ctx).from("dj_tips").select("id, amount_cents, status, song_title, artist, guest_nickname, created_at").eq("dj_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tips: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rwdgnapajxcxktmewlxb";
var mcp_default = defineMcp({
  name: "decks-mcp",
  title: "Decks",
  version: "0.1.0",
  instructions: "Tools for the Decks live-request app. Use `list_my_events` to find the DJ's events, then `list_event_requests`, `get_now_playing`, or `list_recent_tips` to inspect a specific event or earnings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_events_default, list_event_requests_default, get_now_playing_default, list_recent_tips_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
