// D5B typed access to public.request_song.
//
// src/integrations/supabase/types.ts is regenerated by the platform from the
// PRODUCTION schema, and request_song only exists in production once Stage B
// applies 01_d5b_foundation.sql. Until then that file cannot contain the
// function, and editing it directly is blocked by the generator.
//
// The block below is NOT hand-invented: it is the verbatim output of the
// Supabase TypeScript generator (@supabase/postgres-meta typescript template)
// run against the disposable local fixture with 01_d5b_foundation.sql applied.
//
// Stage B removal note: after Stage B regenerates types.ts with request_song,
// delete this file and import { supabase } directly.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { supabase } from "./client";

/** Generated verbatim from the local schema. */
export type RequestSongFunction = {
  Args: {
    _title: string;
    _artist: string;
    _album?: string;
    _album_art_url?: string;
    _duration_ms?: number;
    _external_url?: string;
    _explicit?: boolean;
    _preview_url?: string;
    _event_id: string;
    _source_platform: string;
    _source_song_id: string;
  };
  Returns: {
    outcome: string;
    request_id: string;
  }[];
};

export type DatabaseWithRequestSong = Omit<Database, "public"> & {
  public: Omit<Database["public"], "Functions"> & {
    Functions: Database["public"]["Functions"] & {
      request_song: RequestSongFunction;
    };
  };
};

export type RequestSongArgs = RequestSongFunction["Args"];
export type RequestSongRow = RequestSongFunction["Returns"][number];

/**
 * The same runtime client, typed with the generated request_song signature.
 * Only the client identity is re-typed; every rpc() call through it is fully
 * type-checked (no `as any` anywhere in the request path).
 */
export const supabaseWithRequestSong =
  supabase as unknown as SupabaseClient<DatabaseWithRequestSong>;

export type SupabaseRequestSongClient = typeof supabaseWithRequestSong;
